config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cars do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :bookings, only: [:create, :index, :edit, :update]
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	enum status: [:pending, :confirmed, :rejected]
  belongs_to :user
  belongs_to :car
  has_many :reviews, through: :car
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :model, presence: true
  validates :make, presence: true
  validates :year, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :location, presence: true
  has_one_attached :photo
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch::Model
  pg_search_scope :search_by_car_details,
    against: [ :model, :make, :location ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car
  belongs_to :user

  validates :rating, presence: true
  validates :user, uniqueness: {scope: :car}
  # validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cars, dependent: :destroy
  has_many :bookings
  has_many :bookings_as_owner, through: :cars, source: :bookings
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @bookings = policy_scope(Booking)
    @bookings_as_owner = current_user.bookings_as_owner
    @cars = policy_scope(current_user.cars)
    @review = Review.new
  end

  def new
    @car = Car.find(params[:car_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @car = Car.find(params[:car_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.car = @car
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update(booking_params)
    redirect_to bookings_path
  end

  def edit
  end

  def destroy
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id, :car_id, :status)
  end

  def user_params
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = policy_scope(Car)
    @markers = @cars.geocoded.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { car: car })
      }
    end
    if params[:query].present?
      @cars = Car.search_by_car_details(params[:query])
      @markers = @cars.geocoded.map do |car|
        {
          lat: car.latitude,
          lng: car.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { car: car })
        }
      end
    end
  end

  def show
    @booking = Booking.new
    @car = Car.find(params[:id])
    authorize @car
  end

  def new
    @car = Car.new
    authorize @car
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    authorize @car
    if @car.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def destroy
    @car = Car.find(params[:id])
    authorize @car
    if @car.booking.confirmed? || @car.booking.pending?
      redirect_to bookings_path, notice: 'Cannot update car that has pending bookings.'
    else
      @car.delete
    end
  end

  def edit
    @car = Car.find(params[:id])
    authorize @car
  end

  def update
    @car = Car.find(params[:id])
    authorize @car
    if @car.update(car_params)
      redirect_to bookings_path, notice: 'Car was successfully updated.'
    else
      render :edit
    end
  end


  private

  def car_params
    params.require(:car).permit(:model, :make, :year, :description, :location, :price, :photo, :user_id, :review)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	skip_before_action :authenticate_user!, only: :home
	
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @car = Car.find(params[:car_id])
    @review = Review.new(car: @car)
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @car = Car.find(params[:car_id])
    @review.car = @car
    @review.user = current_user
    authorize @review
    raise
    if @review.save
      redirect_to bookings_path
    else
      @bookings_as_owner = current_user.bookings_as_owner
      @bookings = current_user.bookings
      @cars = current_user.cars
      render 'bookings/index'
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :car_id, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
	end

	def show
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_helper.rb
module BookingHelper
	def get_alert_class(status)
		case status
		when "pending"
			return "flash-warning"
		when "confirmed"
			return "flash-success"
		when "rejected"
			return "flash-danger"
		end
	end
end

app/views/bookings/index.html.erb
<h2 class="mt-3 mb-3" style="text-align:center">My Account</h2>
<%# This is the profile section. Delete if we don't need it any more. %>
<div class="dashboard">
  <!-- Top of dashboard -->
  <div class="dashboard-left">
    <div class="my-profile">
      <div class="my-profile-info">
        <h3>My Profile</h3>
        <% if current_user.photo.attached? %>
          <div class="my-profile-avatar">
            <%= cl_image_tag(current_user.photo.key, crop: :thumb, gravity: :face, class: "avatar-profile" )%>
          </div>
        <% else %>
          <div class="my-profile-avatar">
            <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="avatar-bordered">
          </div>
        <% end %>
        <p><%= current_user.first_name %></p>
        <p>Member since 2018</p>
        <% unless current_user.cars.empty? %>
          <%= link_to "Add car", new_car_path, class: "btn btn-ghost" %>
        <% end %>
      </div>
    </div>
  </div>
  <!-- end of dashboard left -->
  <div class="dashboard-right">
    <div class="tabs">
      <ul class="nav tabs-underlined" id="dashboardTab" role="tablist">
        <li class="nav-item">
          <a class="tab-underlined active" id="booking-tab" data-toggle="tab" href="#booking" role="tab" aria-controls="booking" aria-selected="false">My Bookings</a>
        </li>
        <% unless current_user.cars.empty? %>
          <li class="nav-item">
            <a class="tab-underlined " id="listings-tab" data-toggle="tab" href="#listings" role="tab" aria-controls="listings" aria-selected="true">My Listings</a>
          </li>
          <li class="nav-item">
            <a class="tab-underlined" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">My Cars</a>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade" id="listings" role="tabpanel" aria-labelledby="listings-tab">
        <div class="bookings-of-my-cars">
          <!-- MY LISTINGS NEW -->
          <div class="status">
            <h3> Here are the people who want to rent your car </h3>
            <h3>Pending</h3>
            <% @bookings_as_owner.where(status: "pending").select do |booking| %>
              <div class="flash <%= get_alert_class(booking.status) %> alert alert-dismissible fade show" role="alert">
                <%= cl_image_tag(booking.car.photo.key, crop: :thumb, gravity: :face, class: "w-25", alt: "avatar-large") %>
                <div class="card-product-infos d-flex justify-content-between">
                  <div class="card-product-info-left">
                    <h3><%= booking.car.make %></h3>
                    <div class="card-product-info-middle text-muted">
                      <p>Duration: <%= "#{booking.start_date} 〜 #{booking.end_date} " %></p>
                      <p><%= "Yaller: #{booking.user.first_name}" %></p>
                    </div>
                  </div>
                </div>
                <div class="listings-right-side">
                  <%= simple_form_for booking do |f| %>
                    <%= f.input :status, as: :hidden,input_html: { value: :confirmed } %>
                    <%= f.button :button do %>
                      <i class="status-button-confirm fas fa-check"></i>
                    <% end %>
                  <% end %>
                  <%= simple_form_for booking do |f| %>
                    <%= f.input :status, as: :hidden,input_html: { value: :rejected } %>
                    <%= f.button :button do %>
                      <i class="status-button-reject fas fa-times"></i>
                    <% end %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
          <div class="status">
            <h3>Confirmed</h3>
            <% @bookings_as_owner.where(status: "confirmed").select do |booking| %>
              <div class="flash <%= get_alert_class(booking.status) %> alert alert-dismissible fade show" role="alert">
                <%= cl_image_tag(booking.car.photo.key, crop: :fill, class: "w-25", alt: "avatar-large") %>
                <div class="card-product-infos d-flex align-items-start">
                  <div class="card-product-info-left">
                    <h3><%= booking.car.make %></h3>
                    <div class="card-product-info-middle text-muted">
                      <p>Duration: <%= "#{booking.start_date} 〜 #{booking.end_date} " %></p>
                      <p><%= "Yaller: #{booking.user.first_name}" %></p>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
          <div class="status">
            <h3>Canceled</h3>
            <% @bookings_as_owner.where(status: "rejected").select do |booking| %>
              <div class="flash <%= get_alert_class(booking.status) %> alert alert-dismissible fade show" role="alert">
                <%= cl_image_tag(booking.car.photo.key, crop: :fill, class: "w-25", alt: "avatar-large") %>
                <div class="card-product-infos d-flex align-items-start">
                  <div class="card-product-info-left">
                    <h3><%= booking.car.make %></h3>
                    <div class="card-product-info-middle text-muted">
                      <p>Duration: <%= "#{booking.start_date} 〜 #{booking.end_date} " %></p>
                      <p><%= "Yaller: #{booking.user.first_name}" %></p>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <!-- MY LISTING -->
        <!-- MY LISTINGS ORIGNAL -->
      </div>
      <div class="tab-pane fade show active" id="booking" role="tabpanel" aria-labelledby="booking-tab">
        <div class="bookings-of-my-cars">
          <h2> Here are your reservations </h2>
          <% @bookings.each do |booking| %>
            <div class="flash <%= get_alert_class(booking.status) %> alert alert-dismissible fade show" role="alert">
              <%= cl_image_tag(booking.car.photo.key, crop: :thumb, gravity: :face, class: "avatar-large", alt: "avatar-large") %>
              <div class="card-product-infos">
                <p><%= booking.car.make %></p>
                <p><%= booking.car.model %></p>
                <p>Product description with <strong>relevant info</strong> only.</p>
                <% if booking.confirmed? %>
                  <% if booking.reviews.any?{ |review| review.user == current_user } %>
                    <!-- <p><%= link_to 'Leave a review', new_car_review_path(booking.car)%></p> -->
                    <%= 'Thank you' %>
                  <% else %>
                    <%= render 'reviews/review', car: booking.car, review: @review %>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
        <div class="my-cars">
          <div class="status">
            <h3> My cars available for rent </h3>
            <% @cars.each do |car| %>
              <div class="flash flash-info alert alert-dismissible fade show" role="alert">
                <%= cl_image_tag(car.photo.key, crop: :fill, class: "w-25", alt: "avatar-large") %>
                <div class="card-product-infos">
                  <h3><%= car.make %></h3>
                  <p><%= car.description %></p>
                  <p><%= link_to 'Update the info about this car', edit_car_path(car) %></p>
                  <p><%= link_to 'Delete this car', car, method: :delete, data: { confirm: 'Are you sure?' } %></p>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <%# Content goes here!!!!!!! %>
      </div>
    </div>
    <!-- MY LISTINGS -->
  </div>
</div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <%= simple_form_for [@car, @booking] do |f| %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.submit "Book this car" , class: "btn btn-primary" %>
  <% end %>
</div>

app/views/cars/_info_window.html.erb
<h3><%= car.make %></h3>
<p><%= car.model %></p>
<p>¥<%= car.price %>/day</p>

app/views/cars/edit.html.erb
<div class="container">
  <%= simple_form_for @car do |f| %>
  <%= f.input :model%>
  <%= f.input :make %>
  <%= f.input :year %>
  <%= f.input :description %>
  <%= f.input :location %>
  <%= f.input :price %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Rent my car" , class: "btn btn-primary" %>
  <% end %>
</div>

app/views/cars/index.html.erb
<div class="container">
  <h1 class="mt-3 mb-3" style="text-align:center">All Cars</h1>
  <div class="map-wrapper">
    <div id="map"
        style="width: 100%; height: 300px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%=ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
  <div class="index-page">
    <div class="cards">
      <% @cars.reverse.each do |car| %>
        <div class="card-trip">
          <%= link_to car_path(car) do %>
            <%= cl_image_tag("#{car.photo.key}", crop: :fill) %>
          <% end %>
            <div class="card-trip-infos">
              <div>
                <h2><%= car.make %> <%= car.model%></h2>
                <p><%= car.year%></p>
              </div>
              <div class="card-trip-infos-right-side">
                <h2 class="card-trip-pricing">¥<%= car.price %>/day</h2>
                <% if car.user.photo.attached? %>
                  <div class="card-trip-avatar">
                    <%= cl_image_tag(car.user.photo.key, crop: :thumb, gravity: :face, class: "avatar-bordered" )%>
                  </div>
                <% else %>
                  <div class="card-trip-avatar">
                    <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="avatar-bordered" />
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cars/new.html.erb
<div class="container">
  <%= simple_form_for @car do |f| %>
  <%= f.input :model%>
  <%= f.input :make %>
  <%= f.input :year %>
  <%= f.input :description %>
  <%= f.input :location %>
  <%= f.input :price %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Rent my car" , class: "btn btn-primary" %>
  <% end %>
</div>

app/views/cars/show.html.erb
<div class="container">
  <div class="banner-photo">
    <!--Ask about this start-->
    <% if @car.photo.attached? %>
      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @car.photo.key, height: 300, width: 400, resize: :limit %>);">
      <% else %>
        <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://source.unsplash.com/collection/2328095/1600x900)">
        <% end %>
        <!--Ask about this end-->
        <div class="banner-header">
          <h1><%= @car.make %> <%= @car.model %></h1>
          <p> <%= @car.year %></p>
        </div>
      </div>
    </div>
    <div class="car-info">
      <div class="renter-info">
        <h3>Car Owner:</h3>
        <% if @car.user.photo.attached? %>
          <div class="card-trip-avatar">
            <%= cl_image_tag(@car.user.photo.key, crop: :thumb, gravity: :face, class: "avatar-large", alt: "avatar-large")%>
          </div>
        <% else %>
          <div class="card-trip-avatar">
            <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="avatar-large" />
          </div>
        <% end %>
        <p><%= @car.user.first_name %></p>
        <p>Member since <%= @car.year - 1 %></p>
      </div>
      <div class="car-details">
        <div class="headers">
          <h1><%= @car.year %> <%= @car.make %> <%= @car.model %></h1>
        </div>
        <div class="details-info">
          <p style="text-align:center;">⭐️⭐️⭐️⭐️⭐️ &nbsp; (32) </p>
          <br>
          <p><%= @car.description%></p>
          <br>
        </div>
      </div>
      <div class="booking-form">
        <%= simple_form_for [@car, @booking] do |f| %>
          <%= f.input :start_date, as: :date, html5: true %>
          <%= f.input :end_date, as: :date, html5: true %>
          <h3 class="mt-4 pr-4" id='car-price' data-price='<%= @car.price %>'>&nbsp;&nbsp;¥<%= @car.price %></h3>
          <h5 class="mt-4 mb-0">Total: <span id='form-total-price'>-</span></h5>
          <%= f.submit "Book this car" , class: "btn btn-flat" %>
        <% end %>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YallRides</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%# fonts %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&family=Roboto+Condensed&family=Saira:wght@500&display=swap" rel="stylesheet">
    <%= stylesheet_pack_tag 'application' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="page">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url(https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mnx8Y2FyfGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60);">
    <div class="container">
      <h1>Y'all Rides</h1>
      <p>
        <span id="banner-typed-text"></span>
      </p>
      <div class="search-form-control form-group">
        <%= form_tag cars_path, method: :get do %>
          <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a car or location"
        %>
          <%= submit_tag "Search", class: "btn btn-flat" %>
        <% end %>
      </div>
      <%# <div class="or">
        <p> OR </p>
      </div> %>
      <div class="banner-button">
        <%= link_to "Browse All Cars", cars_path, class: "btn btn-ghost" %>
      </div>
    </div>
  </div>

app/views/reviews/_review.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
<%= simple_form_for [ car, review ] do |f| %>
  <div class="star-rating">
    <% 5.times do |i| %>
      <input type="radio" name="review[rating]" value="<%= i + 1 %>" <%= "checked" if i == 2 %> />
    <% end %>
  </div>
  <br>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/new.html.erb
<div class="container">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">

  <%= simple_form_for [ @car, @review ] do |f| %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>
    <div class="star-rating">
      <% 5.times do |i| %>
        <input type="radio" name="review[rating]" value="<%= i + 1 %>" <%= "checked" if i == 2 %> />
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "yall-rides-logo.png" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
          <li>
            <%= link_to "Add Car", new_car_path, class: "nav-link" %>
          </li>
          <li class ="mr-1">
            <%= current_user.first_name %>
          </li>
        <li class="nav-item dropdown">
          <%= image_tag "portrait.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Account", bookings_path, class: "dropdown-item" %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>